version: '3.4'

services:
  website:
    build:
      dockerfile: Dockerfile
      args:
        source: obj/Docker/empty
    volumes:
      - .\storage\Website\:C:\inetpub\sc\website
    entrypoint: powershell -Command "C:/DebugBoot.ps1;C:/remote_debugger/x64/msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646;C:/ServiceMonitor.exe w3svc;"
